/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package view;

import modelView.Redirect;

/**
 *
 * @author dfmen
 */
public class RegistroParaQuien extends javax.swing.JFrame {

    /**
     * Creates new form Registro_ParaQuien
     */
    public RegistroParaQuien() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        ButtonRegisterForMe = new javax.swing.JButton();
        ButtonRegisterForElse = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel1.setText("Para quien esta destinado el uso de esta app");

        ButtonRegisterForMe.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        ButtonRegisterForMe.setText("Para mi");
        ButtonRegisterForMe.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ButtonRegisterForMeActionPerformed(evt);
            }
        });

        ButtonRegisterForElse.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        ButtonRegisterForElse.setText("Para alguien más");
        ButtonRegisterForElse.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ButtonRegisterForElseActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(39, 39, 39)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(ButtonRegisterForMe, javax.swing.GroupLayout.PREFERRED_SIZE, 164, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(ButtonRegisterForElse, javax.swing.GroupLayout.PREFERRED_SIZE, 174, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(42, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(58, 58, 58)
                .addComponent(jLabel1)
                .addGap(66, 66, 66)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(ButtonRegisterForElse)
                    .addComponent(ButtonRegisterForMe))
                .addContainerGap(184, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void ButtonRegisterForMeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ButtonRegisterForMeActionPerformed
        Redirect.redireccion(4);
    }//GEN-LAST:event_ButtonRegisterForMeActionPerformed

    private void ButtonRegisterForElseActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ButtonRegisterForElseActionPerformed
        Redirect.redireccion(5);
    }//GEN-LAST:event_ButtonRegisterForElseActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton ButtonRegisterForElse;
    private javax.swing.JButton ButtonRegisterForMe;
    private javax.swing.JLabel jLabel1;
    // End of variables declaration//GEN-END:variables
}
